/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedDeductionRouteImport } from './routes/_authenticated/deduction'
import { Route as AuthenticatedEngineeringRouteImport } from './routes/_authenticated/engineering'
import { Route as AuthenticatedFaceRouteImport } from './routes/_authenticated/face'
import { Route as AuthenticatedHabitsRouteImport } from './routes/_authenticated/habits'
import { Route as AuthenticatedImagesRouteImport } from './routes/_authenticated/images'
import { Route as AuthenticatedMetacognitionRouteImport } from './routes/_authenticated/metacognition'
import { Route as AuthenticatedResearchRouteImport } from './routes/_authenticated/research'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedTrendsRouteImport } from './routes/_authenticated/trends'
import { Route as ApiVoiceRouteImport } from './routes/api/voice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeductionRoute = AuthenticatedDeductionRouteImport.update({
  id: '/deduction',
  path: '/deduction',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEngineeringRoute =
  AuthenticatedEngineeringRouteImport.update({
    id: '/engineering',
    path: '/engineering',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFaceRoute = AuthenticatedFaceRouteImport.update({
  id: '/face',
  path: '/face',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHabitsRoute = AuthenticatedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImagesRoute = AuthenticatedImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetacognitionRoute =
  AuthenticatedMetacognitionRouteImport.update({
    id: '/metacognition',
    path: '/metacognition',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResearchRoute = AuthenticatedResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrendsRoute = AuthenticatedTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiVoiceRoute = ApiVoiceRouteImport.update({
  id: '/api/voice',
  path: '/api/voice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedChatRoute
  '/deduction': typeof AuthenticatedDeductionRoute
  '/engineering': typeof AuthenticatedEngineeringRoute
  '/face': typeof AuthenticatedFaceRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/images': typeof AuthenticatedImagesRoute
  '/metacognition': typeof AuthenticatedMetacognitionRoute
  '/research': typeof AuthenticatedResearchRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/trends': typeof AuthenticatedTrendsRoute
  '/api/voice': typeof ApiVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedChatRoute
  '/deduction': typeof AuthenticatedDeductionRoute
  '/engineering': typeof AuthenticatedEngineeringRoute
  '/face': typeof AuthenticatedFaceRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/images': typeof AuthenticatedImagesRoute
  '/metacognition': typeof AuthenticatedMetacognitionRoute
  '/research': typeof AuthenticatedResearchRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/trends': typeof AuthenticatedTrendsRoute
  '/api/voice': typeof ApiVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/deduction': typeof AuthenticatedDeductionRoute
  '/_authenticated/engineering': typeof AuthenticatedEngineeringRoute
  '/_authenticated/face': typeof AuthenticatedFaceRoute
  '/_authenticated/habits': typeof AuthenticatedHabitsRoute
  '/_authenticated/images': typeof AuthenticatedImagesRoute
  '/_authenticated/metacognition': typeof AuthenticatedMetacognitionRoute
  '/_authenticated/research': typeof AuthenticatedResearchRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/_authenticated/trends': typeof AuthenticatedTrendsRoute
  '/api/voice': typeof ApiVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/deduction'
    | '/engineering'
    | '/face'
    | '/habits'
    | '/images'
    | '/metacognition'
    | '/research'
    | '/studio'
    | '/trends'
    | '/api/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/deduction'
    | '/engineering'
    | '/face'
    | '/habits'
    | '/images'
    | '/metacognition'
    | '/research'
    | '/studio'
    | '/trends'
    | '/api/voice'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/chat'
    | '/_authenticated/deduction'
    | '/_authenticated/engineering'
    | '/_authenticated/face'
    | '/_authenticated/habits'
    | '/_authenticated/images'
    | '/_authenticated/metacognition'
    | '/_authenticated/research'
    | '/_authenticated/studio'
    | '/_authenticated/trends'
    | '/api/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiVoiceRoute: typeof ApiVoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deduction': {
      id: '/_authenticated/deduction'
      path: '/deduction'
      fullPath: '/deduction'
      preLoaderRoute: typeof AuthenticatedDeductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engineering': {
      id: '/_authenticated/engineering'
      path: '/engineering'
      fullPath: '/engineering'
      preLoaderRoute: typeof AuthenticatedEngineeringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/face': {
      id: '/_authenticated/face'
      path: '/face'
      fullPath: '/face'
      preLoaderRoute: typeof AuthenticatedFaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habits': {
      id: '/_authenticated/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthenticatedHabitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/images': {
      id: '/_authenticated/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof AuthenticatedImagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metacognition': {
      id: '/_authenticated/metacognition'
      path: '/metacognition'
      fullPath: '/metacognition'
      preLoaderRoute: typeof AuthenticatedMetacognitionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/research': {
      id: '/_authenticated/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AuthenticatedResearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trends': {
      id: '/_authenticated/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof AuthenticatedTrendsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/voice': {
      id: '/api/voice'
      path: '/api/voice'
      fullPath: '/api/voice'
      preLoaderRoute: typeof ApiVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDeductionRoute: typeof AuthenticatedDeductionRoute
  AuthenticatedEngineeringRoute: typeof AuthenticatedEngineeringRoute
  AuthenticatedFaceRoute: typeof AuthenticatedFaceRoute
  AuthenticatedHabitsRoute: typeof AuthenticatedHabitsRoute
  AuthenticatedImagesRoute: typeof AuthenticatedImagesRoute
  AuthenticatedMetacognitionRoute: typeof AuthenticatedMetacognitionRoute
  AuthenticatedResearchRoute: typeof AuthenticatedResearchRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedTrendsRoute: typeof AuthenticatedTrendsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDeductionRoute: AuthenticatedDeductionRoute,
  AuthenticatedEngineeringRoute: AuthenticatedEngineeringRoute,
  AuthenticatedFaceRoute: AuthenticatedFaceRoute,
  AuthenticatedHabitsRoute: AuthenticatedHabitsRoute,
  AuthenticatedImagesRoute: AuthenticatedImagesRoute,
  AuthenticatedMetacognitionRoute: AuthenticatedMetacognitionRoute,
  AuthenticatedResearchRoute: AuthenticatedResearchRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedTrendsRoute: AuthenticatedTrendsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiVoiceRoute: ApiVoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
