// This file is automatically generated. Do not edit it directly.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.15";
  };
  public: {
    Tables: {
      chat_messages: {
        Row: {
          content: string;
          created_at: string;
          id: string;
          provider: string | null;
          role: string;
          user_id: string;
        };
        Insert: {
          content: string;
          created_at?: string;
          id?: string;
          provider?: string | null;
          role: string;
          user_id: string;
        };
        Update: {
          content?: string;
          created_at?: string;
          id?: string;
          provider?: string | null;
          role?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      deduction_attempts: {
        Row: {
          accuracy_score: number | null;
          answer_key: string | null;
          completed_at: string | null;
          created_at: string;
          difficulty: number;
          drill_type: string;
          feedback: string | null;
          id: string;
          prompt: string;
          reasoning_score: number | null;
          recall_due: string | null;
          response: string | null;
          user_id: string;
        };
        Insert: {
          accuracy_score?: number | null;
          answer_key?: string | null;
          completed_at?: string | null;
          created_at?: string;
          difficulty?: number;
          drill_type: string;
          feedback?: string | null;
          id?: string;
          prompt: string;
          reasoning_score?: number | null;
          recall_due?: string | null;
          response?: string | null;
          user_id: string;
        };
        Update: {
          accuracy_score?: number | null;
          answer_key?: string | null;
          completed_at?: string | null;
          created_at?: string;
          difficulty?: number;
          drill_type?: string;
          feedback?: string | null;
          id?: string;
          prompt?: string;
          reasoning_score?: number | null;
          recall_due?: string | null;
          response?: string | null;
          user_id?: string;
        };
        Relationships: [];
      };
      generated_images: {
        Row: {
          created_at: string;
          id: string;
          image_data: string;
          mime_type: string;
          prompt: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          image_data: string;
          mime_type?: string;
          prompt: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          image_data?: string;
          mime_type?: string;
          prompt?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      habit_logs: {
        Row: {
          created_at: string;
          habit_id: string;
          id: string;
          log_date: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          habit_id: string;
          id?: string;
          log_date?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          habit_id?: string;
          id?: string;
          log_date?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "habit_logs_habit_id_fkey";
            columns: ["habit_id"];
            isOneToOne: false;
            referencedRelation: "habits";
            referencedColumns: ["id"];
          },
        ];
      };
      habits: {
        Row: {
          archived: boolean;
          created_at: string;
          id: string;
          name: string;
          notes: string | null;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          archived?: boolean;
          created_at?: string;
          id?: string;
          name: string;
          notes?: string | null;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          archived?: boolean;
          created_at?: string;
          id?: string;
          name?: string;
          notes?: string | null;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      memory_notes: {
        Row: {
          created_at: string;
          id: string;
          key: string;
          source: string;
          updated_at: string;
          user_id: string;
          value: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          key: string;
          source?: string;
          updated_at?: string;
          user_id: string;
          value: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          key?: string;
          source?: string;
          updated_at?: string;
          user_id?: string;
          value?: string;
        };
        Relationships: [];
      };
      metacognition_attempts: {
        Row: {
          biases_identified: Json;
          completed_at: string | null;
          confidence_pct: number;
          correct: boolean | null;
          created_at: string;
          drill_type: string;
          feedback: string | null;
          id: string;
          prompt: string;
          response: string | null;
          score: number | null;
          user_id: string;
        };
        Insert: {
          biases_identified?: Json;
          completed_at?: string | null;
          confidence_pct: number;
          correct?: boolean | null;
          created_at?: string;
          drill_type: string;
          feedback?: string | null;
          id?: string;
          prompt: string;
          response?: string | null;
          score?: number | null;
          user_id: string;
        };
        Update: {
          biases_identified?: Json;
          completed_at?: string | null;
          confidence_pct?: number;
          correct?: boolean | null;
          created_at?: string;
          drill_type?: string;
          feedback?: string | null;
          id?: string;
          prompt?: string;
          response?: string | null;
          score?: number | null;
          user_id?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          created_at: string;
          display_name: string | null;
          id: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          display_name?: string | null;
          id: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          display_name?: string | null;
          id?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      projects: {
        Row: {
          created_at: string;
          id: string;
          source_report_id: string | null;
          status: string;
          summary: string | null;
          title: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          source_report_id?: string | null;
          status?: string;
          summary?: string | null;
          title: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          source_report_id?: string | null;
          status?: string;
          summary?: string | null;
          title?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "projects_source_report_id_fkey";
            columns: ["source_report_id"];
            isOneToOne: false;
            referencedRelation: "research_reports";
            referencedColumns: ["id"];
          },
        ];
      };
      research_reports: {
        Row: {
          body: string;
          created_at: string;
          cross_check: Json | null;
          id: string;
          output_type: string;
          sources: Json;
          topic: string;
          user_id: string;
        };
        Insert: {
          body: string;
          created_at?: string;
          cross_check?: Json | null;
          id?: string;
          output_type?: string;
          sources?: Json;
          topic: string;
          user_id: string;
        };
        Update: {
          body?: string;
          created_at?: string;
          cross_check?: Json | null;
          id?: string;
          output_type?: string;
          sources?: Json;
          topic?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      trend_queries: {
        Row: {
          created_at: string;
          id: string;
          keyword: string;
          results: Json;
          source: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          keyword: string;
          results?: Json;
          source?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          keyword?: string;
          results?: Json;
          source?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      user_settings: {
        Row: {
          created_at: string;
          preferred_language: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          preferred_language?: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          preferred_language?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema["Enums"] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    keyof DefaultSchema["CompositeTypes"] | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;
